### ISSUE TITLE
Bundle/port to a will plugin?

### ISSUE THREAD

**Issue by skoczen** [jessamynsmith/talkbackbot#8]
Hey,

So this isn't really a proper issue, but more of a request / question set.  I found this project via you via your fork of polytester.  I love it.

I also run a hipchat chat bot called [will](https://github.com/skoczen/will). It's one of the more popular hipchat bots, and I would *love* to have talkbackbot's functionality built into will's core. 

So, the request/question.

Would you have any interest in porting this to a [will plugin](http://skoczen.github.io/will/plugins/basics/)? Or, would you mind if I ported it to a will plugin?  If I did the porting though, I'd want to stay current with any changes that happen on talkbackbot.  Ideas on how that'd be best achieved are very welcome.

Anyhow, thanks for making a great project, and your consideration!

**Comment by jessamynsmith** [comment]
Thank you! I like this idea, and I am looking into it.

**Comment by skoczen** [comment]
Fantastic, thanks!  Let me know what I can do to help.

**Comment by jessamynsmith** [comment]
Here is a first cut at a plugin: https://github.com/jessamynsmith/willtalkback
Let me know if I'm doing this correctly... I don't have a server to test on.

**Comment by skoczen** [comment]
This plugin made my week. :)

Code looks totally right - couple tweaks of of raising exceptions instead of logging (will handles them with nice chat/log output) and then updating tests was all I needed to do to plug it here, and it just worked:

![shesaid](https://cloud.githubusercontent.com/assets/200635/6044075/944d9690-acc3-11e4-8777-6f4d8208f947.gif)

Awesome.

As far as integrating, will's typical pattern is that core/common plugins are bundled, and users can enable/disable via a config file.  All org-specific plugins are then built and controlled by the organization /person using will.  The package you've set up would work if people pip installed it, but if it's ok by you, I'd rather just pull this directly into will's core.  (It looks like using underquoted handles keeping it up to date, and fits well with the API-driven plugin pattern used across will.)

I've set up a PR here, for your review and approval/rejection: 
https://github.com/skoczen/will/pull/95/files

If you do approve, please double-check your name in the AUTHORs file, and let me know if you have any changes.

Thanks again!


Oh! Almost forgot - bonus thanks!

Will - somehow, despite his wide usage - doesn't have any tests.  It's is on pretty much everyone's list, but has seemed like one of those Really Hard Problems.  The tests you wrote are a really lovely pattern, and I suspect they'll form the basis of will's test harness abstractions.  So, double thank-you for that.  The power of a smart brain and fresh eyes. :)

**Comment by jessamynsmith** [comment]
Looks good! I'm all about that testing. :)

Do you want to bring over coverage as well? If you are bringing over the
unit tests, I do recommend it. These days I am typically running my code
via coverage, and it's nice to see how you're doing.

I like flake8 a lot, too, but you may not be ready to start flaking your
code just yet. :)

**Comment by skoczen** [comment]
Nice call on coverage - will definitely pull that in.  And flake8 too, at some point.  And actually, I'd love to get it with a nice polytester coverage covering all of those things.  It's how all my work codebases are all set up, and it *is* so lovely. 

But - how big to really make this PR?  Hm. Decisions for the morning, when my brain is no longer jelly. :)

Thanks again, and I'd expect this will go out tomorrow!

**Comment by jessamynsmith** [comment]
Including coverage in dependencies won't hurt much. The rest, yes, bigger
decisions. :)

**Comment by skoczen** [comment]
It's true.  The challenge, of course, is in my head. Once I add coverage, I want to have a proper CD setup (not the terribly scary smoke tests we have now), and then have coverage run as part of CD and once it's in CD, then I actually *need* coverage, and the test harness and several reindeer and probably some kind of tie-in with SpaceX, just to be on the safe side.

Or maybe I should just add coverage in the morning, document it, and call that a start.

**Comment by jessamynsmith** [comment]
I'd go with the latter. Get it in there, and automate it and make it pretty
after. :)

**Comment by skoczen** [comment]
Released as [0.7.0](http://skoczen.github.io/will/improve/#releases) - thanks much for your help & contributions!  Glad to have this as a part of core will - definitely fits in with his personality. :)

**Comment by jessamynsmith** [comment]
Glad to be part of it! I'm quite excited that talkback is getting out there
more.
