### ISSUE TITLE
Casual suggestion - adding the non-apostrophe'd version.

### ISSUE THREAD

**Issue by skoczen** [jessamynsmith/talkbackbot#9]
Hey there,

Just got this PR on the port, and since it seemed really reasonable, figured I'd pass it along and let you see if it made sense for talkbackbot!

https://github.com/skoczen/will/issues/96

**Comment by jessamynsmith** [comment]
The actual talkbackbot is configurable as far as phrases and quotation
source, and it does case insensitive matching. I wasn't sure how to make
the will plugin work the same way, but I think it should.

**Comment by skoczen** [comment]
Got it, makes sense!

The will plugins aren't really general-purpose in that way (other than being case-insensitive, and accepting regexes in the pattern).  

The pattern is to make adding a new method/listener so cheap that adding abstraction/configuration is actually harder/more complicated than just making another one.

It's worked thus far at least!

Thanks again.

**Comment by jessamynsmith** [comment]
Entirely fair!
